127.0.0.1 - - [20/Aug/2025 15:24:49] "HEAD / HTTP/1.1" 200 -
10.2.16.11 - - [20/Aug/2025 15:26:03] "GET / HTTP/1.1" 200 -
10.2.16.11 - - [20/Aug/2025 15:26:07] "GET /download/RL-Sideswipe-Access-v2.19-TENSORFLOW-LITE-ACTIVE-release.apk HTTP/1.1" 200 -
10.2.16.11 - - [20/Aug/2025 15:26:07] "GET /download/RL-Sideswipe-Access-v2.19-TENSORFLOW-LITE-ACTIVE-release.apk HTTP/1.1" 200 -
10.2.16.11 - - [20/Aug/2025 15:26:07] "GET /download/RL-Sideswipe-Access-v2.19-TENSORFLOW-LITE-ACTIVE-release.apk HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('10.2.16.11', 47596)
----------------------------------------
Exception occurred during processing of request from ('10.2.16.11', 47598)
Traceback (most recent call last):
Traceback (most recent call last):
  File "/openhands/micromamba/envs/openhands/lib/python3.12/socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 1311, in finish_request
    self.RequestHandlerClass(request, client_address, self,
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
  File "/openhands/micromamba/envs/openhands/lib/python3.12/socketserver.py", line 766, in __init__
    self.handle()
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 679, in do_GET
    self.copyfile(f, self.wfile)
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 878, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/openhands/micromamba/envs/openhands/lib/python3.12/shutil.py", line 204, in copyfileobj
    fdst_write(buf)
  File "/openhands/micromamba/envs/openhands/lib/python3.12/socketserver.py", line 845, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
  File "/openhands/micromamba/envs/openhands/lib/python3.12/socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 1311, in finish_request
    self.RequestHandlerClass(request, client_address, self,
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
  File "/openhands/micromamba/envs/openhands/lib/python3.12/socketserver.py", line 766, in __init__
    self.handle()
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
----------------------------------------
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 679, in do_GET
    self.copyfile(f, self.wfile)
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 878, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/openhands/micromamba/envs/openhands/lib/python3.12/shutil.py", line 204, in copyfileobj
    fdst_write(buf)
  File "/openhands/micromamba/envs/openhands/lib/python3.12/socketserver.py", line 845, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
10.2.16.11 - - [20/Aug/2025 15:26:10] "GET /download/RL-Sideswipe-Access-v2.19-TENSORFLOW-LITE-ACTIVE-debug.apk HTTP/1.1" 200 -
10.2.16.11 - - [20/Aug/2025 15:26:10] "GET /download/RL-Sideswipe-Access-v2.19-TENSORFLOW-LITE-ACTIVE-debug.apk HTTP/1.1" 200 -
10.2.16.11 - - [20/Aug/2025 15:26:10] "GET /download/RL-Sideswipe-Access-v2.19-TENSORFLOW-LITE-ACTIVE-debug.apk HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('10.2.16.11', 47628)
----------------------------------------
Exception occurred during processing of request from ('10.2.16.11', 47626)
Traceback (most recent call last):
  File "/openhands/micromamba/envs/openhands/lib/python3.12/socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 1311, in finish_request
    self.RequestHandlerClass(request, client_address, self,
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
  File "/openhands/micromamba/envs/openhands/lib/python3.12/socketserver.py", line 766, in __init__
    self.handle()
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
Traceback (most recent call last):
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 679, in do_GET
    self.copyfile(f, self.wfile)
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 878, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/openhands/micromamba/envs/openhands/lib/python3.12/shutil.py", line 204, in copyfileobj
    fdst_write(buf)
  File "/openhands/micromamba/envs/openhands/lib/python3.12/socketserver.py", line 845, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
  File "/openhands/micromamba/envs/openhands/lib/python3.12/socketserver.py", line 697, in process_request_thread
    self.finish_request(request, client_address)
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 1311, in finish_request
    self.RequestHandlerClass(request, client_address, self,
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
  File "/openhands/micromamba/envs/openhands/lib/python3.12/socketserver.py", line 766, in __init__
    self.handle()
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 679, in do_GET
    self.copyfile(f, self.wfile)
  File "/openhands/micromamba/envs/openhands/lib/python3.12/http/server.py", line 878, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/openhands/micromamba/envs/openhands/lib/python3.12/shutil.py", line 204, in copyfileobj
    fdst_write(buf)
  File "/openhands/micromamba/envs/openhands/lib/python3.12/socketserver.py", line 845, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
10.2.24.16 - - [20/Aug/2025 15:26:32] "GET / HTTP/1.1" 304 -
